### ISSUE TITLE
Add RSS Feed

### ISSUE THREAD

**Issue by AntonioCS** [SuperV1234/vittorioromeo.info#6]
Hey,

Can't seem to find an rss feed on your website. Would be easier to get your new posts this way.

Thanks!

**Comment by vittorioromeo** [comment]
Hey Antonio, there is one (but there is no link on the main page). It's generated from the same C++ program, so it's probably not 100% correct/complete *(but it seems to work)*:

https://vittorioromeo.info/index.rss

**Comment by AntonioCS** [comment]
My rss reader seems to like it. 
Maybe in your next iteration on (the huge) main.cpp you can add a rss link on the main page.

Good stuff!
