### ISSUE TITLE
Rss feed not updated!

### ISSUE THREAD

**Issue by AntonioCS** [SuperV1234/vittorioromeo.info#7]
Hey,

The rss feed does not have the new article you posted (http://vittorioromeo.info/index/blog/accu2017_trip_report.html)

**Comment by vittorioromeo** [comment]
I do see it: http://vittorioromeo.info/index.rss

**Comment by AntonioCS** [comment]
I am using sage (firefox addon) as my rss viewer:

![2017-05-01 21_44_39-vittorio romeo s website](https://cloud.githubusercontent.com/assets/1086401/25594318/e22b1f36-2eb7-11e7-9143-d8c21ed43330.png)

There is the list of entries I can see.
You will notice that the rss url I have is https (https://vittorioromeo.info/index.rss). Not sure why I have it as https but it does list all the other articles. 

I have changed it to http and I can now see your new post.
Thanks!
